version: "2"

linters:
  default: none
  enable:
    - errcheck
    - gosec
    - govet
    - ineffassign
    - misspell
    - nolintlint
    - staticcheck
    - unused
  settings:
    gosec:
      excludes:
        - G104
    misspell:
      ignore-rules:
        - packageid

formatters:
  enable:
    - gofumpt
  settings:
    gofumpt:
      extra-rules: true
