version: "2"

linters:
  default: none
  enable:
    - errcheck
    - gosec
    - govet
    - ineffassign
    - misspell
    - nolintlint
    - staticcheck
    - unused
  settings:
    misspell:
      ignore-rules:
        - packageid
    nolintlint:
      require-explanation: true
      require-specific: true

formatters:
  enable:
    - gofumpt
  settings:
    gofumpt:
      extra-rules: true
