{{- if .Values.backup.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "packmon.fullname" . }}-backup
  labels:
    {{- include "packmon.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.backup.storageClassName }}
  storageClassName: {{ .Values.backup.storageClassName | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.backup.size }}
{{- end }}
