apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "packmon.fullname" . }}-config
  labels:
    {{- include "packmon.labels" . | nindent 4 }}
data:
  PACKMON_SERVER_MODE: {{ .Values.server.mode | quote }}
  PACKMON_SERVER_PORT: {{ .Values.server.port | quote }}
  PACKMON_SERVER_READ_TIMEOUT: {{ .Values.server.readTimeout | quote }}
  PACKMON_SERVER_WRITE_TIMEOUT: {{ .Values.server.writeTimeout | quote }}
  PACKMON_SERVER_SHUTDOWN_TIMEOUT: {{ .Values.server.shutdownTimeout | quote }}
  PACKMON_METRICS_HOST: {{ .Values.metrics.host | quote }}
  PACKMON_METRICS_PORT: {{ .Values.metrics.port | quote }}
  PACKMON_ADMIN_SESSION_TIMEOUT: {{ .Values.admin.sessionTimeout | quote }}
  PACKMON_FEED_DATA_DIR: {{ .Values.feeds.dataDir | quote }}
  PACKMON_FEED_OSV_ENABLED: {{ .Values.feeds.osvEnabled | quote }}
  PACKMON_FEED_GHSA_ENABLED: {{ .Values.feeds.ghsaEnabled | quote }}
  PACKMON_FEED_MALICIOUS_ENABLED: {{ .Values.feeds.maliciousEnabled | quote }}
  PACKMON_FEED_VULNCHECK_ENABLED: {{ .Values.feeds.vulncheckEnabled | quote }}
  PACKMON_FEED_SOCKET_ENABLED: {{ .Values.feeds.socketEnabled | quote }}
  PACKMON_FEED_CISAKEV_ENABLED: {{ .Values.feeds.cisakevEnabled | quote }}
  PACKMON_FEED_EPSS_ENABLED: {{ .Values.feeds.epssEnabled | quote }}
  PACKMON_FEED_OSV_MODE: {{ .Values.feeds.osvMode | quote }}
  PACKMON_FEED_GHSA_MODE: {{ .Values.feeds.ghsaMode | quote }}
  PACKMON_FEED_MALICIOUS_MODE: {{ .Values.feeds.maliciousMode | quote }}
  PACKMON_FEED_VULNCHECK_MODE: {{ .Values.feeds.vulncheckMode | quote }}
  PACKMON_FEED_SOCKET_MODE: {{ .Values.feeds.socketMode | quote }}
  PACKMON_FEED_CISAKEV_MODE: {{ .Values.feeds.cisakevMode | quote }}
  PACKMON_FEED_EPSS_MODE: {{ .Values.feeds.epssMode | quote }}
  PACKMON_DB_PORT: {{ ternary "5432" (.Values.externalDatabase.port | toString) .Values.postgresql.enabled | quote }}
  PACKMON_DB_NAME: {{ ternary .Values.postgresql.database .Values.externalDatabase.name .Values.postgresql.enabled | quote }}
  PACKMON_DB_USER: {{ ternary .Values.postgresql.user .Values.externalDatabase.user .Values.postgresql.enabled | quote }}
  PACKMON_DB_HOST: {{ ternary (printf "%s-postgresql" (include "packmon.fullname" .)) .Values.externalDatabase.host .Values.postgresql.enabled | quote }}
  PACKMON_DB_SSLMODE: {{ ternary "disable" .Values.externalDatabase.sslmode .Values.postgresql.enabled | quote }}
