{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "packmon.fullname" . }}-postgresql
  labels:
    {{- include "packmon.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "packmon.name" . }}-postgresql
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
{{- end }}
