{{- /* Validate that a database password is configured. */ -}}
{{- include "packmon.validateDBPassword" . | nindent 0 -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "packmon.fullname" . }}-secret
  labels:
    {{- include "packmon.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-initial-password: {{ .Values.admin.initialPassword | quote }}
  db-password: {{ ternary .Values.postgresql.password .Values.externalDatabase.password .Values.postgresql.enabled | quote }}
  socket-api-key: {{ .Values.feeds.socketApiKey | quote }}
  vulncheck-api-key: {{ .Values.feeds.vulncheckApiKey | quote }}
