package main

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/8linkz/packmon/internal/domain"
)

func writeFile(t *testing.T, path, content string) {
	t.Helper()
	if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
		t.Fatalf("write %s: %v", path, err)
	}
}

func contains(haystack, needle string) bool {
	return strings.Contains(haystack, needle)
}

// stubLatestVersion swaps fetchLatestVersionFn for the duration of the test so
// the list-all package table never makes real network calls.
func stubLatestVersion(t *testing.T, fn func(ctx context.Context, eco domain.Ecosystem, name string) string) {
	t.Helper()
	orig := fetchLatestVersionFn
	fetchLatestVersionFn = fn
	t.Cleanup(func() { fetchLatestVersionFn = orig })
}

// isolatedListAllEnv isolates config discovery and points the local DB at a
// temp directory, mirroring the harness every other scan test uses. Without
// this the scan pipeline touches the real home directory.
func isolatedListAllEnv(t *testing.T) {
	t.Helper()
	isolateCLIConfigDiscovery(t)
	dbDir := t.TempDir()
	t.Setenv("PACKMON_DB_PATH", dbDir)
	store, _ := newTestSQLiteStore(t, dbDir)
	if err := store.Close(); err != nil {
		t.Fatalf("close seed store: %v", err)
	}
}

// seedListAllAdvisory inserts a CRITICAL advisory for npm/vulnpkg@1.0.0 into
// the local SQLite advisory tables so the scanner reports a finding.
func seedListAllAdvisory(t *testing.T, dbDir string) {
	t.Helper()
	store, _ := newTestSQLiteStore(t, dbDir)
	ctx := context.Background()
	if _, err := store.DB().ExecContext(ctx, `
		INSERT INTO vulnerabilities_local(row_key, id, ecosystem, name, version_ranges, severity, summary)
		VALUES('GHSA-listall-test|npm|vulnpkg', 'GHSA-listall-test', 'npm', 'vulnpkg', '[{"introduced":"0.0.0"},{"fixed":"2.0.0"}]', 'CRITICAL', 'list-all test advisory')`); err != nil {
		t.Fatalf("insert vulnerability: %v", err)
	}
}

// listAllSettings builds a minimal local-mode settings struct for a temp dir.
func listAllSettings(dir string, quiet bool) scanSettings {
	return scanSettings{
		TargetName: "x",
		Path:       dir,
		Mode:       "local",
		FailOn:     "CRITICAL",
		MaxDepth:   10,
		Timeout:    30,
		Quiet:      quiet,
		NoColor:    true,
	}
}

func TestRunListAll_ListsAllPackagesWithUpdateInfo(t *testing.T) {
	isolatedListAllEnv(t)
	dir := t.TempDir()
	writeFile(t, filepath.Join(dir, "package-lock.json"), `{
  "name": "test",
  "lockfileVersion": 3,
  "packages": {
    "node_modules/leftpad": { "version": "1.0.0" },
    "node_modules/lodash": { "version": "4.17.15" }
  }
}`)

	// leftpad has a newer version, lodash is up to date.
	stubLatestVersion(t, func(_ context.Context, _ domain.Ecosystem, name string) string {
		switch name {
		case "leftpad":
			return "2.0.0"
		case "lodash":
			return "4.17.15"
		default:
			return ""
		}
	})

	out := captureStdout(t, func() {
		if _, err := runListAll(context.Background(), listAllSettings(dir, false)); err != nil {
			t.Fatalf("runListAll: %v", err)
		}
	})

	// Section 2 header + both packages present.
	for _, col := range []string{"PACKAGE", "INSTALLED", "LATEST", "UPDATE", "ECOSYSTEM", "VULN", "LOCK FILE"} {
		if !contains(out, col) {
			t.Errorf("output missing section-2 column %q:\n%s", col, out)
		}
	}
	if !contains(out, "leftpad") {
		t.Errorf("output missing leftpad:\n%s", out)
	}
	if !contains(out, "lodash") {
		t.Errorf("output missing lodash:\n%s", out)
	}
	if !contains(out, "2.0.0") {
		t.Errorf("output missing leftpad latest version:\n%s", out)
	}
	if !contains(out, "packages (") {
		t.Errorf("output missing summary line:\n%s", out)
	}
}

func TestRunListAll_UnknownLatestWhenResolverReturnsEmpty(t *testing.T) {
	isolatedListAllEnv(t)
	dir := t.TempDir()
	// Resolver failures or unsupported upstream metadata are rendered as
	// "unknown" instead of failing the list-all command.
	writeFile(t, filepath.Join(dir, "pubspec.lock"), `# Generated by pub
packages:
  http:
    dependency: "direct main"
    description:
      name: http
      url: "https://pub.dev"
    source: hosted
    version: "0.13.0"
sdks:
  dart: ">=2.12.0 <3.0.0"
`)

	called := false
	stubLatestVersion(t, func(_ context.Context, _ domain.Ecosystem, _ string) string {
		called = true
		return ""
	})

	out := captureStdout(t, func() {
		if _, err := runListAll(context.Background(), listAllSettings(dir, false)); err != nil {
			t.Fatalf("runListAll: %v", err)
		}
	})

	if !contains(out, "http") {
		t.Errorf("output missing http package:\n%s", out)
	}
	if !contains(out, "unknown") {
		t.Errorf("expected LATEST=unknown when resolver returns empty:\n%s", out)
	}
	if !called {
		t.Errorf("expected fetchLatestVersionFn to be invoked (stub), got no call")
	}
}

func TestRunListAll_UpdateColumnLogic(t *testing.T) {
	isolatedListAllEnv(t)
	dir := t.TempDir()
	writeFile(t, filepath.Join(dir, "package-lock.json"), `{
  "name": "test",
  "lockfileVersion": 3,
  "packages": {
    "node_modules/old": { "version": "1.0.0" },
    "node_modules/current": { "version": "2.0.0" }
  }
}`)

	stubLatestVersion(t, func(_ context.Context, _ domain.Ecosystem, name string) string {
		switch name {
		case "old":
			return "9.9.9"
		case "current":
			return "2.0.0"
		default:
			return ""
		}
	})

	out := captureStdout(t, func() {
		if _, err := runListAll(context.Background(), listAllSettings(dir, false)); err != nil {
			t.Fatalf("runListAll: %v", err)
		}
	})

	lines := strings.Split(out, "\n")
	var oldLine, currentLine string
	for _, l := range lines {
		fields := strings.Fields(l)
		if len(fields) == 0 {
			continue
		}
		switch fields[0] {
		case "old":
			oldLine = l
		case "current":
			currentLine = l
		}
	}
	if oldLine == "" || currentLine == "" {
		t.Fatalf("could not find package rows in output:\n%s", out)
	}
	// Columns: PACKAGE INSTALLED LATEST UPDATE ECOSYSTEM VULN LOCKFILE
	oldFields := strings.Fields(oldLine)
	if len(oldFields) < 4 || oldFields[3] != "yes" {
		t.Errorf("expected UPDATE=yes for old, got line: %q", oldLine)
	}
	currentFields := strings.Fields(currentLine)
	if len(currentFields) < 4 || currentFields[3] != "-" {
		t.Errorf("expected UPDATE=- for current, got line: %q", currentLine)
	}
}

func TestRunListAll_VulnerablePackageAppearsInBothSections(t *testing.T) {
	isolatedListAllEnv(t)
	dbDir := os.Getenv("PACKMON_DB_PATH")

	// Seed an advisory for vulnpkg@1.0.0 so the scanner reports a finding.
	seedListAllAdvisory(t, dbDir)

	dir := t.TempDir()
	writeFile(t, filepath.Join(dir, "package-lock.json"), `{
  "name": "test",
  "lockfileVersion": 3,
  "packages": {
    "node_modules/vulnpkg": { "version": "1.0.0" },
    "node_modules/safe": { "version": "2.0.0" }
  }
}`)

	stubLatestVersion(t, func(_ context.Context, _ domain.Ecosystem, name string) string {
		switch name {
		case "vulnpkg":
			return "1.0.1"
		case "safe":
			return "2.0.0"
		default:
			return ""
		}
	})

	out := captureStdout(t, func() {
		if _, err := runListAll(context.Background(), listAllSettings(dir, false)); err != nil {
			t.Fatalf("runListAll: %v", err)
		}
	})

	// Section 1: finding for vulnpkg.
	if !contains(out, "GHSA-listall-test") && !contains(out, "vulnpkg") {
		t.Errorf("expected section-1 finding referencing vulnpkg:\n%s", out)
	}

	// Section 2: vulnpkg row with VULN=yes; safe row with VULN=-.
	lines := strings.Split(out, "\n")
	var vulnLine, safeLine string
	for _, l := range lines {
		fields := strings.Fields(l)
		if len(fields) == 0 {
			continue
		}
		switch fields[0] {
		case "vulnpkg":
			vulnLine = l
		case "safe":
			safeLine = l
		}
	}
	if vulnLine == "" || safeLine == "" {
		t.Fatalf("could not find package rows in section 2:\n%s", out)
	}
	// VULN is column index 5 (0-based): PACKAGE INSTALLED LATEST UPDATE ECOSYSTEM VULN LOCKFILE
	vf := strings.Fields(vulnLine)
	if len(vf) < 6 || vf[5] != "yes" {
		t.Errorf("expected VULN=yes for vulnpkg, got line: %q", vulnLine)
	}
	sf := strings.Fields(safeLine)
	if len(sf) < 6 || sf[5] != "-" {
		t.Errorf("expected VULN=- for safe, got line: %q", safeLine)
	}
}

func TestRunListAll_FindingsSectionRendersTable(t *testing.T) {
	isolatedListAllEnv(t)
	dir := t.TempDir()
	writeFile(t, filepath.Join(dir, "package-lock.json"), `{
  "name": "test",
  "lockfileVersion": 3,
  "packages": {
    "node_modules/leftpad": { "version": "1.0.0" }
  }
}`)
	stubLatestVersion(t, func(_ context.Context, _ domain.Ecosystem, _ string) string {
		return ""
	})

	out := captureStdout(t, func() {
		if _, err := runListAll(context.Background(), listAllSettings(dir, false)); err != nil {
			t.Fatalf("runListAll: %v", err)
		}
	})

	// Local mode with empty advisory DB -> no findings. The normal scan still
	// prints a "No findings" summary line.
	if !contains(out, "No findings") {
		t.Errorf("expected findings-section summary line:\n%s", out)
	}
}

func TestRunListAll_QuietSuppressesHumanOutput(t *testing.T) {
	isolatedListAllEnv(t)
	dir := t.TempDir()
	writeFile(t, filepath.Join(dir, "package-lock.json"), `{
  "name": "test",
  "lockfileVersion": 3,
  "packages": {
    "node_modules/leftpad": { "version": "1.0.0" }
  }
}`)
	stubLatestVersion(t, func(_ context.Context, _ domain.Ecosystem, _ string) string {
		return "2.0.0"
	})

	out := captureStdout(t, func() {
		if _, err := runListAll(context.Background(), listAllSettings(dir, true)); err != nil {
			t.Fatalf("runListAll: %v", err)
		}
	})

	if strings.TrimSpace(out) != "" {
		t.Errorf("expected no stdout in quiet mode, got:\n%s", out)
	}
}
