package parser

import (
	"strings"
	"testing"

	"github.com/8linkz-sec/packmon/internal/domain"
)

func TestCargoParser_CanParse(t *testing.T) {
	t.Parallel()
	p := NewCargoParser()

	tests := []struct {
		filename string
		want     bool
	}{
		{"Cargo.lock", true},
		{"cargo.lock", true}, // case-insensitive
		{"CARGO.LOCK", true}, // case-insensitive
		{"Cargo.toml", false},
		{"package-lock.json", false},
		{"", false},
	}

	for _, tt := range tests {
		if got := p.CanParse(tt.filename); got != tt.want {
			t.Errorf("CanParse(%q) = %v, want %v", tt.filename, got, tt.want)
		}
	}
}

func TestCargoParser_Ecosystem(t *testing.T) {
	t.Parallel()
	if got := NewCargoParser().Ecosystem(); got != domain.EcosystemCargo {
		t.Errorf("Ecosystem() = %q, want %q", got, domain.EcosystemCargo)
	}
}

func TestCargoParser_Parse(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name      string
		input     string
		wantCount int
		wantPkgs  map[string]string
		wantErr   bool
	}{
		{
			name: "valid Cargo.lock",
			input: `# This file is automatically @generated by Cargo.
[[package]]
name = "serde"
version = "1.0.197"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "tokio"
version = "1.37.0"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "rand"
version = "0.8.5"
source = "registry+https://github.com/rust-lang/crates.io-index"
`,
			wantCount: 3,
			wantPkgs: map[string]string{
				"serde": "1.0.197",
				"tokio": "1.37.0",
				"rand":  "0.8.5",
			},
		},
		{
			name:      "empty file",
			input:     "",
			wantCount: 0,
		},
		{
			name:    "invalid toml",
			input:   `{{{not toml`,
			wantErr: true,
		},
		{
			name: "entry missing version",
			input: `[[package]]
name = "serde"
version = "1.0.197"

[[package]]
name = "broken"
version = ""
`,
			wantCount: 1,
			wantPkgs:  map[string]string{"serde": "1.0.197"},
			wantErr:   true,
		},
		{
			name: "entry missing name",
			input: `[[package]]
name = ""
version = "1.0.0"

[[package]]
name = "serde"
version = "1.0.197"
`,
			wantCount: 1,
			wantPkgs:  map[string]string{"serde": "1.0.197"},
			wantErr:   true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			pkgs, err := NewCargoParser().Parse(strings.NewReader(tt.input))
			if tt.wantErr {
				if err == nil {
					t.Fatal("expected error, got nil")
				}
				if len(pkgs) != tt.wantCount {
					t.Fatalf("got %d packages, want %d (with error)", len(pkgs), tt.wantCount)
				}
				return
			}
			if err != nil {
				t.Fatalf("unexpected error: %v", err)
			}
			if len(pkgs) != tt.wantCount {
				t.Fatalf("got %d packages, want %d", len(pkgs), tt.wantCount)
			}
			for _, pkg := range pkgs {
				if pkg.Ecosystem != domain.EcosystemCargo {
					t.Errorf("package %q ecosystem = %q, want %q", pkg.Name, pkg.Ecosystem, domain.EcosystemCargo)
				}
				if wantVer, ok := tt.wantPkgs[pkg.Name]; ok {
					if pkg.Version != wantVer {
						t.Errorf("package %q version = %q, want %q", pkg.Name, pkg.Version, wantVer)
					}
				}
			}
		})
	}
}
